version: '3.8'
services:
  node-server:
    container_name: node
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb  # Ensures the node server container starts after the MongoDB container
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: frontendtest
      MONGO_INITDB_ROOT_PASSWORD: nsFj9F7YTW2BvnwZ
    networks:
      - mongodb_network

networks:
  mongodb_network:

volumes:
  mongodb_data:
    driver: local
