version: '3.8'
services:
  node-server: # Node server container
    container_name: node-server
    build: .
    ports:
      - "8000:8000"
    command: node app.js
    volumes:
      - ./app.js:/app.js 
    depends_on:
      - mongodb  # Ensures the node server container starts after the MongoDB container
  
  nginx: # Nginx container
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf 
    depends_on:
      - node-server  # Ensures the Nginx container starts after the Node server container

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: frontendtest
      MONGO_INITDB_ROOT_PASSWORD: nsFj9F7YTW2BvnwZ
    networks:
      - mongodb_network

  node-dashboard:
    container_name: node-dashboard
    build: . 
    ports:
      - "8100:8100"
    command: node dashboard.js
    volumes:
      - ./dashboard.js:/dashboard.js

  node-settings:
    container_name: node-settings
    build: . 
    ports:
      - "8200:8200"
    command: node setting.js
    volumes:
      - ./setting.js:/setting.js

networks:
  mongodb_network:

volumes:
  mongodb_data:
    driver: local
